# coding: utf-8
from sqlalchemy import Column, DECIMAL, Date, DateTime, String, text
from sqlalchemy.dialects.mysql import VARCHAR
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class INDICBASEPOSBOND(Base):
    __tablename__ = 'INDIC_BASE_POS_BOND'
    __table_args__ = {'comment': '债券持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='估值日期')
    PRODUCT_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合代码')
    ASSET_UNIT_CODE = Column(VARCHAR(100), comment='资产单元代码')
    STRATEGY_CODE = Column(VARCHAR(100), comment='策略代码')
    ACCOUNT_CODE = Column(VARCHAR(100), comment='子账户代码')
    SECU_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='证券内码')
    SECU_TYPE = Column(VARCHAR(100), comment='证券类型')
    SYMBOL = Column(VARCHAR(100), comment='证券代码')
    SECU_NAME = Column(String(100), comment='证券名称')
    MARKET_CODE = Column(VARCHAR(100), comment='交易市场')
    PS_TYPE_CODE = Column(VARCHAR(100), comment='持有类型')
    CURRENCY = Column(VARCHAR(100), comment='币种')
    PS_COST = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='成本_期初')
    PE_COST = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='成本_期末')
    CHG_COST = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='成本变化')
    PS_UNIT_COST = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='单位成本_期初')
    PE_UNIT_COST = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='单位成本_期末')
    PS_VALUATION_PRICE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='估值价格_期初')
    PE_VALUATION_PRICE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='估值价格_期末')
    PS_VALUATION_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='估值数量_期初')
    PE_VALUATION_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='估值数量_期末')
    CLEAN_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='净价')
    DIRTY_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='全价')
    OUTFLOW_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='流出应计利息')
    INFLOW_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='流入应计利息')
    BUY_UNSETTLE_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='买入未交收费用')
    EFFECTIVE_RATE = Column(DECIMAL(28, 20), server_default=text("'0.00000000000000000000'"), comment='实际利率')
    PS_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期初')
    PE_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期末')
    PE_SHADOW_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='影子市值_期末')
    PS_SHADOW_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='影子市值_期初')
    PS_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_期初')
    PE_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_期末')
    CHG_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_发生额')
    TRADING_FEE_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日交易费用')
    BUY_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日买入金额')
    BUY_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日买入数量')
    SELL_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日卖出金额')
    SELL_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日卖出数量')
    PS_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期初 （6101）')
    CHG_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_发生额 （6101）')
    PE_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期末 （6101）')
    PS_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期初 （6111）')
    CHG_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_发生额 （6111）')
    PE_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期末 （6111）')
    PS_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_期初 （6011）')
    CHG_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_发生额 （6011）')
    PE_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_期末 （6011）')
    BUY_TRADING_FEE_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日买入交易费用')
    SELL_TRADING_FEE_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日卖出交易费用')
    BUY_UNSETTLE_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='买入未交收金额')
    BUY_UNSETTLE_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='买入未交收数量')
    BUY_UNSETTLE_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='买入未结算利息')
    SELL_UNSETTLE_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='卖出未交收金额')
    SELL_UNSETTLE_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='卖出未交收数量')
    SELL_UNSETTLE_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='卖出未结算利息')
    PS_DISCOUNT_PREMIUM = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='折溢价_期初')
    CHG_DISCOUNT_PREMIUM = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='折溢价_发生额')
    PE_DISCOUNT_PREMIUM = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='折溢价_期末')
    RESIDUAL_MATURITY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='剩余期限')
    RESIDUAL_DURATION = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='剩余存续期')
    PS_VALUE_ADDED_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='增值税_期初')
    CHG_VALUE_ADDED_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='增值税_发生额')
    PE_VALUE_ADDED_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='增值税_期末')
    INTEREST_TAX_RATE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息税税率')
    OUT_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='流出成本')
    PS_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_期初')
    CHG_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_发生额')
    PE_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_期末')
    BD_FLOAT_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='浮动盈亏')
    BD_MKTVAL_PORT_AST_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券市值占组合总资产比例')
    BD_MKTVAL_PORT_NAV_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券持仓市值占组合资产净值比例')
    BD_DAILY_RETURN_RAT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='个券收益率')
    BD_MKTVAL_BD_TOTMKTV_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券市值占债券总市值比例')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='更新时间')
    EMBD_OPT_FLAG = Column(String(3), comment='含权债标识 1是0否')
    PERP_BOND_FLAG = Column(String(3), comment='永续债标识 1是0 否')
    CITY_INVT_FLAG = Column(String(3), comment='城投债标识 1是 0否')
    BREAK_FLAG = Column(VARCHAR(3), comment='违约标识  1是 0否')
    LATEST_BD_OUT_RATING = Column(String(100), comment='最新债项外部评级')


class INDICBASEPOSBONDLEND(Base):
    __tablename__ = 'INDIC_BASE_POS_BOND_LEND'
    __table_args__ = {'comment': '债券借贷持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(String(30), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_CODE = Column(String(30), primary_key=True, nullable=False, comment='组合代码')
    PORTFOLIO_TYPE = Column(String(30), primary_key=True, nullable=False, comment='组合类型')
    ASSET_UNIT_CODE = Column(String(30), comment='资产单元')
    STRATEGY_CODE = Column(String(30), comment='策略编码')
    ACCOUNT_CODE = Column(String(30), comment='账户编码')
    EXECUTION_CODE = Column(String(30), primary_key=True, nullable=False, comment='成交编号')
    SECU_CODE = Column(String(30), comment='证券内码')
    SECU_TYPE = Column(String(30), comment='证券类型')
    SYMBOL = Column(String(30), comment='证券外码')
    MARKET_CODE = Column(String(30), comment='市场代码')
    CURRENCY = Column(String(30), comment='币种')
    EXCHANGE_RATE = Column(DECIMAL(22, 8), comment='汇率')
    UNDY_SECU_CODE = Column(String(30), comment='标的券内码')
    UNDY_SECU_SYMBOL = Column(String(30), comment='标的券外码')
    UNDY_SECU_QTY = Column(DECIMAL(22, 0), comment='标的券数量')
    PAR_AMT = Column(DECIMAL(22, 4), comment='票面金额')
    LEND_RATE = Column(DECIMAL(22, 8), comment='借贷费率')
    NOM_AMT = Column(DECIMAL(22, 4), comment='名义本金')
    LEND_DAYS = Column(DECIMAL(22, 0), comment='借贷天数')
    FIRST_SETTLE_DATE = Column(Date, comment='首期结算日')
    MATURE_SETTLE_DATE = Column(Date, comment='到期结算日')
    PE_AI = Column(DECIMAL(22, 4), comment='应收利息_期末')
    CHG_AI = Column(DECIMAL(22, 4), comment='应收利息_发生额')
    PS_AI = Column(DECIMAL(22, 4), comment='应收利息_期初')
    PS_INTEREST_EXPENSE = Column(DECIMAL(22, 4), comment='利息支出_期初')
    CHG_INTEREST_EXPENSE = Column(DECIMAL(22, 4), comment='利息支出_发生额')
    PE_INTEREST_EXPENSE = Column(DECIMAL(22, 4), comment='利息支出_期末')
    MATURE_INTEREST = Column(DECIMAL(22, 4), comment='到期利息')
    PAYABLE_TRADING_FEE = Column(DECIMAL(22, 4), comment='应付交易费用_发生额')
    CHG_TRADING_EXPENSE = Column(DECIMAL(22, 4), comment='交易费用_发生额')
    CHG_SETTLEMENT_AMT = Column(DECIMAL(22, 4), comment='证券清算款_发生额')
    CHG_CURRENT_DEPOSIT_AMT = Column(DECIMAL(22, 4), comment='活期存款_发生额')
    UPDATE_TIME = Column(DateTime, comment='更新日期')
    CREATE_TIME = Column(DateTime, comment='创建日期')


class INDICBASEPOSDEPOSIT(Base):
    __tablename__ = 'INDIC_BASE_POS_DEPOSIT'
    __table_args__ = {'comment': '存款持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    DEPOSIT_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='存单编号')
    PRODUCT_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合代码')
    ASSET_UNIT_CODE = Column(VARCHAR(100), comment='资产单元代码')
    STRATEGY_CODE = Column(VARCHAR(100), comment='策略代码')
    ACCOUNT_CODE = Column(VARCHAR(100), comment='子账户代码')
    MARKET_CODE = Column(VARCHAR(100), comment='市场代码')
    DEPOSIT_TYPE = Column(VARCHAR(100), comment='存款类型')
    BANK_PARTY_HCODE = Column(VARCHAR(100), comment='存款银行')
    BANK_BRANCH_PARTY_HCODE = Column(VARCHAR(100), comment='存款分支行')
    CURRENCY = Column(VARCHAR(100), comment='币种')
    AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='存款金额（本金）')
    PS_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='持仓成本_期初')
    PE_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='持仓成本_期末')
    DEPOSIT_RATE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='存款利率')
    VALUE_DATE = Column(Date, comment='起息日')
    DUE_DATE = Column(Date, comment='到期日')
    INTEREST_DAYS = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='计息天数')
    PS_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_期初')
    PE_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_期末')
    DEPOSIT_DATE = Column(Date, comment='存款日期')
    PS_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_期初')
    CHG_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_发生额')
    PE_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_期末')
    RESIDUAL_MATURITY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='剩余期限')
    CHG_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_发生额')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='更新时间')
    MKTVAL_PORT_AST_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券占组合总资产比例')
    MKTVAL_PORT_NAV_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券占组合净资产比例')


class INDICBASEPOSFUND(Base):
    __tablename__ = 'INDIC_BASE_POS_FUND'
    __table_args__ = {'comment': '基金持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合代码')
    ASSET_UNIT_CODE = Column(VARCHAR(100), comment='资产单元代码')
    STRATEGY_CODE = Column(VARCHAR(100), comment='策略代码')
    ACCOUNT_CODE = Column(VARCHAR(100), comment='子账户代码')
    SECU_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='证券内码')
    SECURITY_ACCOUNT_CODE = Column(VARCHAR(100), comment='证券账户')
    SECU_TYPE = Column(VARCHAR(100), comment='证券类型')
    SYMBOL = Column(VARCHAR(100), comment='证券代码')
    SECU_NAME = Column(String(100), comment='证券名称')
    MARKET_CODE = Column(VARCHAR(100), comment='交易市场')
    CURRENCY = Column(VARCHAR(100), comment='币种')
    PS_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='成本_期初')
    PE_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='成本_期末')
    CHG_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='成本_发生额')
    UNIT_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='单位持仓成本')
    PS_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期初')
    PE_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期末')
    PS_VALUATION_QTY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值数量_期初')
    PE_VALUATION_QTY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值数量_期末')
    PS_VALUATION_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值价格_期初')
    PE_VALUATION_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值价格_期末')
    PS_FROZEN_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='冻结数量_期初')
    PE_FROZEN_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='冻结数量_期末')
    BUY_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日买入金额')
    SELL_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日卖出金额')
    BUY_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日买入数量')
    SELL_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日卖出数量')
    BUY_TRADE_FEE_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日买入交易费用')
    SELL_TRADE_FEE_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日卖出交易费用')
    PS_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期初 （6101）')
    CHG_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_发生额 （6101）')
    PE_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期末 （6101）')
    PS_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期初 （6111）')
    CHG_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_发生额 （6111）')
    PE_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期末 （6111）')
    PS_RECEIVABLE_DIVIDEND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收红利_期初')
    CHG_RECEIVABLE_DIVIDEND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收红利_发生额')
    PE_RECEIVABLE_DIVIDEND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收红利_期末')
    PS_DIVIDEND_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='红利收入_期初')
    CHG_DIVIDEND_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='红利收入_发生额')
    PE_DIVIDEND_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='红利收入_期末')
    PS_VALUE_ADDED_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='增值税_期初')
    CHG_VALUE_ADDED_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='增值税_发生额')
    PE_VALUE_ADDED_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='增值税_期末')
    OUT_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='流出成本')
    FD_FLOAT_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='浮动盈亏')
    FD_MKTVAL_PORT_AST_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='基金市值占组合总资产比例')
    FD_MKTVAL_PORT_NAV_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='基金持仓市值占组合资产净值比例')
    FD_DAILY_RETURN_RAT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='基金日收益率')
    FD_MKTVAL_FD_TOTMKTV_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='基金市值占基金总市值比例')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='更新时间')


class INDICBASEPOSFUTURE(Base):
    __tablename__ = 'INDIC_BASE_POS_FUTURE'
    __table_args__ = {'comment': '期货持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合代码')
    ASSET_UNIT_CODE = Column(VARCHAR(100), comment='资产单元代码')
    STRATEGY_CODE = Column(VARCHAR(100), comment='策略代码')
    ACCOUNT_CODE = Column(VARCHAR(100), comment='子账户代码')
    SECU_CODE = Column(VARCHAR(100), comment='证券内码')
    TRADE_DIR = Column(VARCHAR(100), comment='交易方向')
    SECU_TYPE = Column(VARCHAR(100), comment='证券类型')
    SYMBOL = Column(VARCHAR(100), comment='证券代码')
    SECU_NAME = Column(String(100), comment='证券名称')
    MARKET_CODE = Column(VARCHAR(100), comment='交易市场')
    CURRENCY = Column(VARCHAR(100), comment='币种')
    CONTRACT_MULTIPLIER = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='合约乘数')
    MIN_MARGIN_RATIO = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='最低交易保证金率')
    PS_VALUATION_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='合约数量_期初')
    PE_VALUATION_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='合约数量_期末')
    OPEN_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日开仓数量')
    CLOSE_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日平仓数量')
    PS_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='合约价值_期初')
    CHG_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='合约价值_发生额')
    PE_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='合约价值_期末')
    PS_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期初')
    PE_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期末')
    OPEN_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日开仓合约价值')
    CLOSE_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日平仓合约价值')
    PS_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期初 （6101）')
    CHG_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_发生额 （6101）')
    PE_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期末 （6101）')
    PS_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期初 （6111）')
    CHG_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_发生额 （6111）')
    PE_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期末 （6111）')
    PS_VALUATION_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='昨日结算价')
    PE_VALUATION_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日结算价')
    PE_SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金_期末（1021）')
    PS_SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金_期初（1021）')
    PE_MARGIN_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易保证金_期末')
    PS_MARGIN_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易保证金_期初')
    CHG_SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金_发生额（1021）')
    CHG_MARGIN_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易保证金_发生额')
    OUT_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='流出成本')
    TRADE_FEE_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易费用')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='更新时间')
    INVEST_TYPE = Column(String(20), nullable=False, comment='投资类型')
    POSITION_FLAG = Column(String(20), nullable=False, comment='多空标志')
    DATA_SOURCE = Column(String(100), nullable=False, comment='数据来源')
    EXCHANGE_RATE = Column(DECIMAL(16, 4), comment='汇率')
    DAILY_VALUATION_QTY = Column(DECIMAL(18, 0), comment='当日估值数量')
    UNIT_COST = Column(DECIMAL(19, 4), comment='单位成本')
    PS_MARGIN_RATIO = Column(DECIMAL(22, 4), comment='期初保证金比例')
    PE_MARGIN_RATIO = Column(DECIMAL(22, 4), comment='期末保证金比例')
    DAILY_SETTLEMENT_AMT = Column(DECIMAL(22, 4), comment='证券清算款_当日发生额')
    DAILY_CURRENT_DEPOSIT_AMT = Column(DECIMAL(22, 4), comment='活期存款_当日发生额')
    DAILY_VALUE_ADDED_TAX = Column(DECIMAL(22, 4), comment='增值税_当日发生额')
    MKTVAL_PORT_AST_RAT = Column(DECIMAL(22, 8), comment='个券占组合总资产比例')
    MKTVAL_PORT_NAV_RAT = Column(DECIMAL(22, 8), comment='个券占组合净资产比例')
    DAILY_PAYABLE_TRADING_FEE = Column(DECIMAL(22, 4), comment='应付交易费用_当日发生额')


class INDICBASEPOSNONSTD(Base):
    __tablename__ = 'INDIC_BASE_POS_NONSTD'
    __table_args__ = {'comment': '非标持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='持仓日期')
    PRODUCT_CODE = Column(String(28), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_CODE = Column(String(28), primary_key=True, nullable=False, comment='投资组合代码')
    PORTFOLIO_TYPE = Column(String(20), primary_key=True, nullable=False, comment='投资组合类型')
    DATA_SOURCE = Column(String(20), nullable=False, comment='数据来源')
    SECU_CODE = Column(String(28), primary_key=True, nullable=False, comment='证券代码（内码）')
    SYMBOL = Column(String(20), comment='证券代码（外码）')
    INVEST_TYPE = Column(String(20), comment='持有类型<>ps_type_h=H=持有到期&ps_type_c=C=可流通&ps_type_a=A=可供出售')
    MARKET_CODE = Column(String(20), comment='交易市场')
    SECU_TYPE = Column(String(20), comment='证券类型')
    CURRENCY = Column(String(20), comment='币种')
    EXCHANGE_RATE = Column(DECIMAL(14, 4), server_default=text("'0.0000'"), comment='汇率')
    PS_COST = Column(DECIMAL(19, 4), server_default=text("'0.0000'"), comment='成本_期初（上一日）')
    PE_COST = Column(DECIMAL(19, 4), server_default=text("'0.0000'"), comment='成本_期末')
    PS_VALUATION_PRICE = Column(DECIMAL(16, 4), server_default=text("'0.0000'"), comment='估值价格_期初（上一日）')
    PE_VALUATION_PRICE = Column(DECIMAL(16, 4), server_default=text("'0.0000'"), comment='估值价格_期末')
    PS_VALUATION_QTY = Column(DECIMAL(16, 4), server_default=text("'0.0000'"), comment='估值数量_期初')
    PE_VALUATION_QTY = Column(DECIMAL(16, 4), server_default=text("'0.0000'"), comment='估值数量_期末')
    PS_MKT = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='市值_期初(上一日)')
    PE_MKT = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='市值_期末')
    PE_AI = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='应计利息_期末')
    CHG_AI = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='应计利息_当日发生额')
    PS_AI = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='应计利息_期初(上一日)')
    PS_DISCOUNT_PREMIUM = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='折溢价_期初（上一日）')
    CHG_DISCOUNT_PREMIUM = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='折溢价_当日发生额')
    PE_DISCOUNT_PREMIUM = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='折溢价_期末')
    PS_VALUE_GL = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='估值损益_期初 （上一日）')
    CHG_VALUE_GL = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='估值损益_当日发生额')
    PE_VALUE_GL = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='估值损益_期末')
    PS_INTEREST_INCOME = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='利息收入_期初 （上一日）')
    CHG_INTEREST_INCOME = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='利息收入_当日发生额')
    PE_INTEREST_INCOME = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='利息收入_期末')
    PS_INVESTEMENT_INCOME = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='投资收益_期初 （上一日）')
    CHG_INVESTEMENT_INCOME = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='投资收益_当日发生额')
    PE_INVESTEMENT_INCOME = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='投资收益_期末')
    CHG_VALUE_ADDED_TAX = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='增值税_当日发生额')
    CHG_SETTLEMENT_AMT = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='证券清算款_当日发生额')
    CHG_CURRENT_DEPOSIT_AMT = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='活期存款_当日发生额')
    TRADE_FEE_DAY = Column(DECIMAL(20, 4), server_default=text("'0.0000'"), comment='交易费（6407）')
    ASSET_UNIT_CODE = Column(String(30), comment='资产单元代码')
    STRATEGY_CODE = Column(String(30), comment='策略代码')
    ACCOUNT_CODE = Column(String(30), comment='子账户代码')
    UPDATE_TIME = Column(Date, comment='更新时间')
    DEVALUE_STAGE = Column(String(16), comment='减值阶段')
    PS_DEVALUE_AMT = Column(DECIMAL(22, 4), nullable=False, server_default=text("'0.0000'"), comment='减值金额_期初')
    CHG_DEVALUE_AMT = Column(DECIMAL(22, 4), nullable=False, server_default=text("'0.0000'"), comment='减值金额_发生额')
    PE_DEVALUE_AMT = Column(DECIMAL(22, 4), nullable=False, server_default=text("'0.0000'"), comment='减值金额_期末')
    CHG_DEVALUE_EXPENSE = Column(DECIMAL(22, 4), nullable=False, server_default=text("'0.0000'"), comment='减值损失_发生额')
    MKTVAL_PORT_AST_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券占组合总资产比例')
    MKTVAL_PORT_NAV_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券占组合净资产比例')


class INDICBASEPOSOPTION(Base):
    __tablename__ = 'INDIC_BASE_POS_OPTION'
    __table_args__ = {'comment': '期权持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合代码')
    ASSET_UNIT_CODE = Column(VARCHAR(100), comment='资产单元')
    STRATEGY_CODE = Column(VARCHAR(100), comment='策略')
    ACCOUNT_CODE = Column(VARCHAR(100), comment='子账户')
    SECU_CODE = Column(VARCHAR(100), comment='证券内码')
    CTR_DIR = Column(VARCHAR(100), comment='合约方向')
    CTR_TYPE = Column(VARCHAR(100), comment='期权类型')
    SECU_TYPE = Column(VARCHAR(100), comment='证券类型')
    SYMBOL = Column(VARCHAR(100), comment='证券代码')
    SECU_NAME = Column(String(100), comment='证券名称')
    MARKET_CODE = Column(VARCHAR(100), comment='交易市场')
    CURRENCY = Column(VARCHAR(100), comment='币种')
    CTR_UNT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='合约单位')
    PS_VALUATION_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='合约数量_期初')
    PE_VALUATION_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='合约数量_期末')
    OPEN_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日开仓数量')
    CLOSE_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日平仓数量')
    PS_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='合约价值_期初')
    CHG_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='合约价值_发生额')
    PE_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='合约价值_期末')
    PS_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期初')
    PE_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期末')
    OPEN_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日开仓合约价值')
    CLOSE_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日平仓合约价值')
    PS_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期初 （6101）')
    CHG_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_发生额 （6101）')
    PE_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期末 （6101）')
    PS_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期初 （6111）')
    CHG_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_发生额 （6111）')
    PE_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期末 （6111）')
    PS_VALUATION_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='昨日结算价')
    PE_VALUATION_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日结算价')
    CALL_TRADE_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日认购交易费')
    PUT_TRADE_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日认沽交易费')
    DUE_DATE = Column(Date, comment='到期日【行权日】')
    PE_SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金_期末（1021）')
    CHG_SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金_发生额（1021）')
    PS_SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金_期初（1021）')
    OUT_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='流出成本')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='更新时间')


class INDICBASEPOSREPO(Base):
    __tablename__ = 'INDIC_BASE_POS_REPO'
    __table_args__ = {'comment': '回购持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    EXECUTION_CODE = Column(String(100), primary_key=True, nullable=False, comment='成交编号')
    PRODUCT_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合代码')
    ASSET_UNIT_CODE = Column(VARCHAR(100), comment='资产单元代码')
    STRATEGY_CODE = Column(VARCHAR(100), comment='策略代码')
    ACCOUNT_CODE = Column(VARCHAR(100), comment='子账户代码')
    TRADE_TYPE_CODE = Column(VARCHAR(100), nullable=False, comment='交易类型（正回购_逆回购）')
    COUNTER_PARTY = Column(VARCHAR(100), comment='对手方')
    SECU_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='证券编码')
    SYMBOL = Column(VARCHAR(100), comment='证券代码')
    SECU_NAME = Column(String(100), comment='证券名称')
    SECU_TYPE = Column(VARCHAR(100), comment='证券类别')
    MARKET_CODE = Column(VARCHAR(100), comment='交易市场')
    CURRENCY = Column(VARCHAR(100), comment='币种')
    PS_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_期初')
    CHG_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_发生额')
    PE_AI = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应计利息_期末')
    TRADE_DATE = Column(Date, comment='交易日')
    FIRST_CLEAR_DATE = Column(Date, comment='首期清算日')
    FIRST_SETTLE_DATE = Column(Date, comment='首期交收日')
    END_CLEAR_DATE = Column(Date, comment='到期清算日')
    END_SETTLE_DATE = Column(Date, comment='到期交收日')
    AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='回购金额')
    OCCUPANCY_DAYS = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='实际占用天数')
    REPO_RATE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='回购利率')
    REPO_TERM = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='回购期限')
    TRADE_FEE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='交易费')
    COMMISSION_FEE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='佣金')
    PS_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='持仓成本_期初')
    CHG_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='持仓成本_发生额')
    PE_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='持仓成本_期末')
    EFFECTIVE_YIELD = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='实际收益率')
    RESIDUAL_MATURITY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='剩余期限')
    FEE_IN_COST = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='计入成本费用')
    NET_PROFIT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='回购净收益')
    PS_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_期初')
    CHG_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_变化')
    PE_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_期末')
    TOTAL_ACCRUED_INTEREST = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='总应计利息')
    TOTAL_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总金额')
    SETTLE_SPEED = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='清算速度')
    PS_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_期初')
    CHG_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_发生额')
    PE_INTEREST_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息收入_期末')
    PAID_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='已付交易费用')
    PAYABLE_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付交易费用')
    TOTAL_INTEREST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息总额')
    PLEDGE_BONDS = Column(VARCHAR(500), comment='质押券的secuCode,多个时候用,分隔')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='更新时间')
    BROKER_CODE = Column(VARCHAR(1))
    TRADE_SEAT = Column(VARCHAR(1))
    MKTVAL_PORT_AST_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券占组合总资产比例')
    MKTVAL_PORT_NAV_RAT = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='个券占组合净资产比例')


class INDICBASEPOSSTOCK(Base):
    __tablename__ = 'INDIC_BASE_POS_STOCK'
    __table_args__ = {'comment': '股票持仓表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(String(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(String(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(String(100), primary_key=True, nullable=False, comment='投资组合代码')
    ASSET_UNIT_CODE = Column(String(100), comment='资产单元代码')
    STRATEGY_CODE = Column(String(100), comment='策略代码')
    ACCOUNT_CODE = Column(String(100), comment='子账户代码')
    SECU_CODE = Column(String(100), primary_key=True, nullable=False, comment='证券内码')
    SECU_TYPE = Column(String(100), comment='证券类型')
    SYMBOL = Column(String(100), comment='证券代码')
    SECU_NAME = Column(String(500), comment='证券名称')
    MARKET_CODE = Column(String(100), comment='市场代码')
    CURRENCY = Column(String(100), comment='币种')
    EXCHANGE_RATE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='汇率')
    PS_VALUATION_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='估值数量_期初')
    PE_VALUATION_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='估值数量_期末')
    PS_FROZEN_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='冻结数量_期初')
    PE_FROZEN_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='冻结数量_期末')
    CHG_DIVIDEND_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='股利收入_发生额')
    PS_DIVIDEND_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='股利收入_期初')
    PE_DIVIDEND_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='股利收入_期末')
    CHG_RECEIVABLE_DIVIDEND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收股利_发生额')
    PS_RECEIVABLE_DIVIDEND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收股利_期初')
    PE_RECEIVABLE_DIVIDEND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收股利_期末')
    PS_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='持仓成本_期初')
    CHG_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='持仓成本_发生额')
    PE_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='持仓成本_期末')
    OUT_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='流出成本')
    UNIT_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='单位持仓成本')
    BUY_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日买入金额')
    SELL_AMT_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日卖出金额')
    BUY_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日买入数量')
    SELL_QTY_DAY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='当日卖出数量')
    BUY_TRADE_FEE_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日买入交易费用')
    SELL_TRADE_FEE_DAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日卖出交易费用')
    PS_VALUATION_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值价格_期初')
    PE_VALUATION_PRICE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值价格_期末')
    PS_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期初')
    PE_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='市值_期末')
    CHG_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易费用_发生额(6407)')
    PS_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易费用_期初(6407)')
    PE_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易费用_期末(6407)')
    CHG_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_发生额 (6111)')
    PS_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期初 (6111)')
    PE_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期末 (6111)')
    CHG_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_发生额  (6101)')
    PS_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期初 (6101)')
    PE_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='估值损益_期末 (6101)')
    PS_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_期初')
    CHG_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_发生额')
    PE_ACCUM_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='累计盈亏_期末')
    STK_FLOAT_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='浮动盈亏')
    STK_MKTVAL_PORT_AST_RAT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='个股市值占组合总资产比例')
    STK_MKTVAL_PORT_NETAST_RAT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='个股持仓市值占组合资产净值比例')
    STK_DAILY_RETURN_RAT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='个股日收益率')
    STK_MKTVAL_STK_TOTMKTV_RAT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='个股市值占股票总市值比例')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='更新时间')
    ST_FLAG = Column(String(3), comment='ST股标识 1是 0否')
    SUSP_FLAG = Column(String(3), comment='停牌标识')
    UNPUB_ISSUE_FLAG = Column(String(3), comment='非公开发行 1是 0否')
    NEW_STK_FLAG = Column(String(3), comment='新股标识 1是 0否')
    CIRCULATE_FLAG = Column(String(3), comment='流通标识')
    LOCK_QTY = Column(DECIMAL(22, 0), server_default=text("'0'"), comment='锁定数量')
    UN_CIRCULATION_PRICE = Column(DECIMAL(22, 4), comment='非流通价格')
    UN_CIRCULATION_QTY = Column(DECIMAL(22, 0), comment='非流通数量')
    UN_CIRCULATION_MKTV = Column(DECIMAL(22, 4), comment='非流通市值')


class INDICBASEVALASSET(Base):
    __tablename__ = 'INDIC_BASE_VAL_ASSET'
    __table_args__ = {'comment': '估值资产表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(VARCHAR(100), primary_key=True, nullable=False, comment='投资组合代码')
    ASSET_UNIT_CODE = Column(VARCHAR(100), comment='资产单元')
    STRATEGY_CODE = Column(VARCHAR(100), comment='策略')
    ACCOUNT_CODE = Column(VARCHAR(100), comment='子账户')
    PE_TOTAL_ASSET = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总资产_期末')
    PS_TOTAL_ASSET = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总资产_期初')
    PE_TOTAL_ASSET_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总资产_期末成本')
    PE_TOTAL_LIABILITIES = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总负债_期末')
    PS_TOTAL_LIABILITIES = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总负债_期初')
    PE_NET_ASSET = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='净资产_期末')
    PS_NET_ASSET = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='净资产_期初')
    PE_SHARES = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='份额_期末')
    PS_SHARES = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='份额_期初')
    PE_UNIT_NAV = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='单位净值_期末')
    PS_UNIT_NAV = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='单位净值_期初')
    ACCU_UNIT_NAV = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='累计单位净值')
    ACCU_NAV_GROWTH_RATE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='累计净值增长率')
    ADJ_UNIT_NAV = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='复权单位净值')
    MKTV_STOCK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='股票投资市值')
    COST_STOCK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='股票投资成本')
    MKTV_BOND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='债券投资市值')
    COST_BOND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='债券投资成本')
    MKTV_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='基金投资市值')
    COST_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='基金投资成本')
    MKTV_ASSET_BACK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='资产支持证券市值')
    COST_ASSET_BACK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='资产支持证券成本')
    MKTV_FUTURE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='期货投资市值')
    MKTV_BUY_REPO = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='卖出回购资产市值')
    MKTV_SELL_REPO = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='买入返售市值')
    MKTV_OTHER_DERIVATIVE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他衍生品市值')
    MKTV_SHADOW_BOND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='债券投资影子市值')
    MKTV_SHADOW_ASSET_BACK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='资产支持证券影子市值')
    MKTV_FORWARD = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='远期投资市值')
    MKTV_OPTION = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='权证投资市值')
    COST_OPTION = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='权证投资成本')
    COST_REALIZABLE_BOND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='可变现债券成本')
    COST_TREASURY_BOND = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='国债成本')
    COST_POLICY_BOND = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='政策性金融债成本')
    COST_CENTRAL_BANK_BILL = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='央行票据成本')
    COST_DEPOSIT_IN_5DAYS = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='5个工作日内到期定期存款成本')
    COST_OTHER_BOND_IN_5DAYS = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='5个工作日内到期其他债券成本')
    COST_REVERSE_REPO_IN_5DAYS = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='5个工作日内到期逆回购成本')
    TOTAL_DEPOSIT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='银行存款总金额（1002 银行存款）')
    PS_CURRENT_DEPOSIT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='活期存款余额_期初')
    PE_CURRENT_DEPOSIT_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='活期存款应计利息_期末')
    PS_CURRENT_DEPOSIT_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='活期存款应计利息_期初')
    PE_CURRENT_DEPOSIT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='活期存款金额_期末（1002 银行存款 下级科目）')
    TERM_DEPOSIT_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='定期存款应收利息')
    TERM_DEPOSIT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='定期存款金额')
    BOND_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='债券应收利息')
    REPO_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='回购应收利息')
    ASSET_BACK_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='资产支持证券应收利息')
    INTEREST_RECEIVABLE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='应收利息金额（1204）')
    PS_INTEREST_INCOME = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='利息收入_期初（6011）')
    PE_INTEREST_INCOME = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='利息收入_期末（6011）')
    SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='证券清算款（3003）')
    PE_IB_SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='银行间证券清算款_期末')
    PS_IB_SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='银行间证券清算款_期初')
    PE_SZ_SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='深圳证券清算款_期末')
    PS_SZ_SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='深圳证券清算款_期初')
    PE_SH_SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='上海证券清算款_期末')
    PS_SH_SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='上海证券清算款_期初')
    PS_OTC_SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='场外证券清算款_期初')
    PE_OTC_SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='场外证券清算款_期末')
    CAPITAL_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='实收资本金额（4001 实收基金）')
    PE_SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金_期末（1021）')
    PS_SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金_期初（1021）')
    CASH_TOTAL_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='现金总额')
    CASH_RATIO = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='现金比例')
    PS_SETTLEMENT_FUND_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='备付金利息_期初')
    PE_SETTLEMENT_FUND_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='备付金利息_期末')
    PE_MARGIN_FUND_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='保证金利息_期末')
    PS_MARGIN_FUND_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='保证金利息_期初')
    PE_PROVISION_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='预提费用_期末（2501）')
    PS_PROVISION_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='预提费用_期初（2501）')
    PE_SUBSCRIBE_RECEIVABLE_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收申购款_期末(1207)')
    PS_SUBSCRIBE_RECEIVABLE_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收申购款_期初(1207)')
    PE_MKTV_DIVIDEND_RECEIVABLE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收股利_期末（1203）')
    PS_MKTV_DIVIDEND_RECEIVABLE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收股利_期初（1203）')
    PE_OTHER_RECEIVABLE_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他应收款_期末（1221）')
    PS_OTHER_RECEIVABLE_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他应收款_期初（1221）')
    PE_PAYABLE_SALES_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付销售服务费_期末（2208）')
    PS_PAYABLE_SALES_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付销售服务费_期初（2208）')
    PE_PAYABLE_CUSTODIAN_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付托管费_期末（2207）')
    PS_PAYABLE_CUSTODIAN_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付托管费_期初（2207）')
    PE_PAYABLE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付税费_期末（2221）')
    PS_PAYABLE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付税费_期初（2221）')
    PE_PAYABLE_REDEMPTION_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付赎回款_期末（2203）')
    PS_PAYABLE_REDEMPTION_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付赎回款_期初（2203）')
    PE_PAYABLE_REDEMPTION_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付赎回费_期末（2204）')
    PS_PAYABLE_REDEMPTION_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付赎回费_期初（2204）')
    PE_PAYABLE_INTEREST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付利息_期末（2231）')
    PS_PAYABLE_INTEREST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付利息_期初（2231）')
    PE_PAYABLE_PROFIT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付利润_期末（2232）')
    PS_PAYABLE_PROFIT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付利润_期初（2232）')
    PE_PAYABLE_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付交易费_期末（2209）')
    PS_PAYABLE_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付交易费_期初（2209）')
    PE_PAYABLE_MGT_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付管理费_期末（2206）')
    PS_PAYABLE_MGT_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付管理费_期初（2206）')
    PE_PAYABLE_OTHER_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他应付款_期末（2241）')
    PS_PAYABLE_OTHER_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他应付款_期初（2241）')
    PS_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='公允价值变动损益_期初(6101)')
    PE_VALUE_GL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='公允价值变动损益_期末(6101)')
    PS_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期初(6111)')
    PE_INVESTEMENT_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='投资收益_期末(6111)')
    PS_OTHER_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他收入_期初(6302)')
    PE_OTHER_INCOME = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他收入_期末(6302)')
    PS_PRIOR_PERIOD_GL_ADJ = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='以前年度损益调整_期初(6901)')
    PE_PRIOR_PERIOD_GL_ADJ = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='以前年度损益调整_期末(6901)')
    PE_MARGIN_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='存出保证金_期末（1031 存出保证金）')
    PS_MARGIN_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='存出保证金_期初（1031 存出保证金）')
    INCOME_TODAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日收入')
    EXPEND_TODAY = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日支出')
    DAILY_PNL = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='日盈亏')
    PROFIT_PER10K_SHARES_A = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='万份收益A')
    PROFIT_PER10K_SHARES_B = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='万份收益B')
    SEVEN_DAYS_ANN_YIELD_A = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='7日年化收益A')
    SEVEN_DAYS_ANN_YIELD_B = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='7日年化收益B')
    SEVEN_DAYS_ANN_YIELD = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='七日年化收益')
    PROFITPER10KSHARES = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='万份收益')
    TOTAL_PROFIT_PER10KSHARES = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='累计万份收益')
    NAV_DAILY_GROWTH_RATE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='日单位净值增长率')
    DAILY_RETURN = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='日收益率')
    VALUE_ADDED_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='增值税')
    EDU_SURCHARGE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='教育附加税')
    LOCAL_EDU_SURCHARGE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='地方教育附加税')
    CONSTRUCTION_SURCHARGE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='城建附加税')
    PE_UNAMORTIZED_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='待摊费用_期末（1501）')
    PS_UNAMORTIZED_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='待摊费用_期初（1501）')
    PS_MANAGEMENT_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='管理人报酬_期初(6403)')
    PE_MANAGEMENT_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='管理人报酬_期末(6403)')
    PS_CUSTODIAN_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='托管费_期初(6404)')
    PE_CUSTODIAN_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='托管费_期末(6404)')
    PS_SALES_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='销售服务费_期初(6406)')
    PE_SALES_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='销售服务费_期末(6406)')
    PS_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易费用_期初(6407)')
    PE_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='交易费用_期末(6407)')
    PS_INTEREST_EXPENSE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息支出_期初(6411)')
    PE_INTEREST_EXPENSE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='利息支出_期末(6411)')
    PS_OTHER_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他费用_期初(6605)')
    PE_OTHER_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他费用_期末(6605)')
    F_AVG_RESIDUAL_DURATION_BOND = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='平均剩余存续期因子_债券')
    F_AVG_RESIDUAL_MATURITY_BOND = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='平均剩余期限因子_债券')
    F_AVG_RESIDUAL_MATURITY_DEPO = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='平均剩余期限因子_存款')
    F_AVG_RESIDUAL_MATURITY_REPO = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='平均剩余期限因子_回购')
    RESIDUAL_MATURITY = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='剩余期限')
    AVG_RESIDUAL_DURATION = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='平均剩余存续期')
    AVG_RESIDUAL_MATURITY = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='平均剩余期限')
    LEVERAGE_RATE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='杠杆率')
    DEVIATION = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='偏离度')
    IRBOND_ASSET_IN_5DAYS = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='现金利率债及五日内到期资产')
    LIMITED_LIQUIDITY_ASSET = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='流动性受限资产')
    LIMITED_LIQUIDITY_ASSET_RATIO = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='流动性受限资产比例')
    IRBOND_ASSET_IN_5DAYS_RATIO = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='现金利率债及五日内到期资产占比')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment='更新时间')
    SHADOW_TOT_ASSET = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='影子总资产')
    SHADOW_NET_ASSET = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='影子净资产')
    DAILY_PAYABLE_TAX = Column(DECIMAL(22, 4), comment='应付税费_当日发生额')
    DAILY_INTEREST_INCOME = Column(DECIMAL(22, 4), comment='利息收入_当日发生额')
    DAILY_VALUE_PNL = Column(DECIMAL(22, 4), comment='估值损益_当日发生额')
    DAILY_DIVIDEND_INCOME = Column(DECIMAL(22, 4), comment='红利收入_当日发生额')
    DAILY_INVEST_INCOME = Column(DECIMAL(22, 4), comment='投资收益_当日发生额')
    DAILY_OTHER_INCOME = Column(DECIMAL(22, 4), comment='其他收入_当日发生额')
    DAILY_MGT_EXPENSE = Column(DECIMAL(22, 4), comment='管理人报酬_当日发生额')
    DAILY_CUSTODIAN_EXPENSE = Column(DECIMAL(22, 4), comment='托管费_当日发生额')
    DAILY_SALES_EXPENSE = Column(DECIMAL(22, 4), comment='销售服务费_当日发生额')
    DAILY_TRADING_EXPENSE = Column(DECIMAL(22, 4), comment='交易费用_当日发生额')
    DAILY_INTEREST_EXPENSE = Column(DECIMAL(22, 4), comment='利息支出_当日发生额')
    DAILY_OTHER_EXPENSE = Column(DECIMAL(22, 4), comment='其他费用_当日发生额')


class VALUATIONPORTPOSDTL(Base):
    __tablename__ = 'VALUATION_PORT_POS_DTL'
    __table_args__ = {'comment': '组合持仓明细表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(VARCHAR(20), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_CODE = Column(VARCHAR(20), nullable=False, comment='投资组合代码')
    CURRENCY = Column(VARCHAR(50), comment='币种')
    EXC_RATE = Column(DECIMAL(22, 8), comment='汇率')
    AST_CLS_CODE = Column(VARCHAR(10), comment='资产大类，股票、基金等')
    SEC_TYPE = Column(VARCHAR(10), comment='证券类型')
    MARKET_CODE = Column(VARCHAR(10), comment='交易市场')
    INV_CLS_CODE = Column(VARCHAR(10), comment='投资分类代码')
    LMT_CLS_TYPE_CODE = Column(VARCHAR(10), primary_key=True, nullable=False, comment='受限流通类型代码')
    SECU_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='证券内码')
    SYMBOL = Column(VARCHAR(50), comment='证券代码')
    SECU_NAME = Column(VARCHAR(100), comment='证券名称')
    HLD_QTY = Column(DECIMAL(18, 0), comment='持仓数量')
    UNIT_COST_O = Column(DECIMAL(22, 4), comment='单位成本-原币')
    UNIT_COST_L = Column(DECIMAL(22, 4), comment='单位成本-本币')
    HLD_COST_O = Column(DECIMAL(22, 4), comment='成本-原币')
    HLD_COST_L = Column(DECIMAL(22, 4), comment='成本-本币')
    COST_NAV_RATE_O = Column(DECIMAL(22, 8), comment='成本占净值比例-原币')
    COST_NAV_RATE_L = Column(DECIMAL(22, 8), comment='成本占净值比例-本币')
    COST_AST_RATE_O = Column(DECIMAL(22, 8), comment='成本占总资产比例-原币')
    COST_AST_RATE_L = Column(DECIMAL(22, 8), comment='成本占总资产比例-本币')
    VALUATION_PRICE = Column(DECIMAL(22, 4), comment='估值价格')
    HLD_MKTV_O = Column(DECIMAL(22, 4), comment='市值-原币')
    HLD_MKTV_L = Column(DECIMAL(22, 4), comment='市值-本币')
    MKTV_NAV_RATE_O = Column(DECIMAL(22, 8), comment='市值占净值-原币')
    MKTV_NAV_RATE_L = Column(DECIMAL(22, 8), comment='市值占净值-本币')
    MKTV_AST_RATE_O = Column(DECIMAL(22, 8), comment='市值占总资产-原币')
    MKTV_AST_RATE_L = Column(DECIMAL(22, 8), comment='市值占总资产-本币')
    VALUATION_ADD_AMT_O = Column(DECIMAL(22, 4), comment='估值增值-原币')
    VALUATION_ADD_AMT_L = Column(DECIMAL(22, 4), comment='估值增值-本币')
    ACCD_INTEREST_O = Column(DECIMAL(22, 4), comment='应计利息-原币')
    ACCD_INTEREST_L = Column(DECIMAL(22, 4), comment='应计利息-本币')
    RECEIVABLE_DIVIDEND_O = Column(DECIMAL(22, 4), comment='应收股利-原币')
    RECEIVABLE_DIVIDEND_L = Column(DECIMAL(22, 4), comment='应收股利-本币')
    DISCOUNT_PREMIUM_O = Column(DECIMAL(22, 4), comment='溢折价-原币')
    DISCOUNT_PREMIUM_L = Column(DECIMAL(22, 4), comment='溢折价-本币')
    DEVALUE_AMT_O = Column(DECIMAL(22, 4), comment='减值准备-原币')
    DEVALUE_AMT_L = Column(DECIMAL(22, 4), comment='减值准备-本币')
    DEVALUE_EXPENSE_O = Column(DECIMAL(22, 4), comment='减值损失-原币')
    DEVALUE_EXPENSE_L = Column(DECIMAL(22, 4), comment='减值损失-本币')
    SHADOW_PRICE = Column(DECIMAL(22, 4), comment='影子价格')
    SUBPEND_INFO = Column(VARCHAR(200), comment='停牌信息')
    RIGHTS_INFO = Column(VARCHAR(200), comment='权益信息')
    UPDATE_TIME = Column(DateTime, comment='更新时间')
