# coding: utf-8
from sqlalchemy import Column, Date, DateTime, Numeric, String, Text, text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class ProductParseConfig(Base):
    __tablename__ = 'product_parse_config'

    product_id = Column(String(30), primary_key=True, nullable=False, comment='产品内码')
    product_code = Column(String(30), comment='产品代码')
    product_name = Column(String(100), comment='产品名称')
    file_biz_type = Column(String(10), primary_key=True, nullable=False, comment='文件业务类型')
    file_keywords = Column(String(200), comment='文件名称关键字')
    config_content = Column(Text, comment='配置内容')
    memo = Column(String(200), comment='备注')
    create_time = Column(DateTime, comment='创建日期')
    update_time = Column(DateTime, comment='更新日期')


class QdiiFundUnderlyingPostionBloomberg(Base):
    __tablename__ = 'qdii_fund_underlying_postion_bloomberg'

    id = Column(String(30), primary_key=True, nullable=False, comment='id')
    biz_date = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    biz_time = Column(DateTime, nullable=False)
    product_code = Column(String(30), nullable=False, comment='产品代码（预留）')
    secu_name = Column(String(200), nullable=False, comment='证券简称')
    secu_trade_code = Column(String(30), comment='证券代码（ISIN）')
    curr_qty = Column(Numeric(22, 6), comment='当前净头寸')
    unit_cost = Column(Numeric(22, 6), comment='成本价')
    market_price = Column(Numeric(22, 8), comment='市场价格')
    mktv = Column(Numeric(22, 6), comment='持有市值')
    ytd_total_pnl = Column(Numeric(22, 6), comment='当年累计总损益')
    ytd_urlze_pnl = Column(Numeric(22, 6), comment='当年累计未实现损益')
    ytd_rlze_pnl = Column(Numeric(22, 6), comment='当年累计已实现损益')
    ytd_interest_income = Column(Numeric(22, 6), comment='当年累计利息收入')
    daily_totl_pal = Column(Numeric(22, 6), comment='当天总损益')
    daily_urlze_pal = Column(Numeric(22, 6), comment='当天未实现损益')
    daily_rlze_pal = Column(Numeric(22, 6), comment='当天已实现损益')
    daily_interest_income = Column(Numeric(22, 6), comment='当天利息收入')
    par = Column(Numeric(22, 6), comment='面值')
    coupon_rate = Column(Numeric(12, 8), comment='票面利率')
    bid_price_modif_dur = Column(Numeric(22, 6), comment='买价修正久期')
    dv01 = Column(Numeric(22, 6), comment='DV01')
    bid_price_ytw = Column(Numeric(22, 6), comment='买价YTW')
    ask_price_ytw = Column(Numeric(22, 6), comment='卖价YTW')
    inn_rating = Column(String(30), comment='内部评级')
    moody_issur_rating = Column(String(30), comment='穆迪发行人评级')
    fitch_issur_rating = Column(String(30), comment='惠誉发行人评级')
    sp_issu_rating = Column(String(30), comment='S&P发行人评级')
    issur = Column(String(100), comment='发行人')
    guartr = Column(String(100), comment='担保人')
    industry = Column(String(100), comment='行业')
    industry_group = Column(String(100), comment='行业小组')
    industry_brch_group = Column(String(100), comment='行业分支小组')
    due_date = Column(Date, comment='到期日期')
    matr_type = Column(String(20), comment='到期类型')
    remn_term_year = Column(Numeric(22, 6), comment='剩余期限(年）')
    redem_date = Column(Date, comment='赎回日期')
    dcdate = Column(Date, comment='批处理日期')
    dcprocesstime = Column(DateTime, comment='批处理时间')


class ValfileCapitalAcctBal(Base):
    __tablename__ = 'valfile_capital_acct_bal'

    biz_date = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    product_code = Column(String(100), primary_key=True, nullable=False, comment='产品代码')
    portfolio_type = Column(String(100), primary_key=True, nullable=False, comment='投资组合类型')
    portfolio_code = Column(String(100), nullable=False, comment='投资组合代码')
    acct_code = Column(String(50), primary_key=True, nullable=False, comment='账户号')
    acct_name = Column(String(200), comment='账户名称')
    acct_type_code = Column(String(50), nullable=False, comment='账户类型')
    cur_code = Column(String(10), comment='币种代码')
    exch_rate = Column(Numeric(22, 8), server_default=text("1.0000"), comment='汇率')
    hld_bal = Column(Numeric(22, 4), server_default=text("0.0000"), comment='持有余额（不含利息）')
    hld_interest_bal = Column(Numeric(22, 4), server_default=text("0.0000"), comment='持有利息余额')
    create_time = Column(DateTime, comment='创建时间')
    update_time = Column(DateTime, comment='更新时间')


class ValfilePortIndex(Base):
    __tablename__ = 'valfile_port_index'

    biz_date = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    product_code = Column(String(100), primary_key=True, nullable=False, comment='产品代码')
    portfolio_type = Column(String(100), primary_key=True, nullable=False, comment='投资组合类型')
    portfolio_code = Column(String(100), primary_key=True, nullable=False, comment='投资组合代码')
    total_asset_mktv = Column(Numeric(22, 4), server_default=text("0.0000"), comment='总资产市值')
    total_asset_cost = Column(Numeric(22, 4), server_default=text("0.0000"), comment='总资产成本')
    total_liabilities_mktv = Column(Numeric(22, 4), server_default=text("0.0000"), comment='总负债市值')
    total_liabilities_cost = Column(Numeric(22, 4), server_default=text("0.0000"), comment='总负债成本')
    net_asset_mktv = Column(Numeric(22, 4), server_default=text("0.0000"), comment='净资产市值')
    net_asset_cost = Column(Numeric(22, 4), server_default=text("0.0000"), comment='净资产成本')
    shares = Column(Numeric(22, 4), server_default=text("0.0000"), comment='份额')
    unit_nav = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='单位净值')
    accu_unit_nav = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='累计单位净值')
    accu_nav_growth_rate = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='累计净值增长率')
    mktv_stock = Column(Numeric(22, 4), server_default=text("0.0000"), comment='股票投资市值')
    cost_stock = Column(Numeric(22, 4), server_default=text("0.0000"), comment='股票投资成本')
    mktv_bond = Column(Numeric(22, 4), server_default=text("0.0000"), comment='债券投资市值')
    cost_bond = Column(Numeric(22, 4), server_default=text("0.0000"), comment='债券投资成本')
    mktv_fund = Column(Numeric(22, 4), server_default=text("0.0000"), comment='基金投资市值')
    cost_fund = Column(Numeric(22, 4), server_default=text("0.0000"), comment='基金投资成本')
    mktv_asset_back = Column(Numeric(22, 4), server_default=text("0.0000"), comment='资产支持证券市值')
    cost_asset_back = Column(Numeric(22, 4), server_default=text("0.0000"), comment='资产支持证券成本')
    cost_nonstd = Column(Numeric(22, 4), server_default=text("0.0000"), comment='非标成本')
    mktv_nonstd = Column(Numeric(22, 4), server_default=text("0.0000"), comment='非标市值')
    mktv_future = Column(Numeric(22, 4), server_default=text("0.0000"), comment='期货投资市值')
    mktv_buy_repo = Column(Numeric(22, 4), server_default=text("0.0000"), comment='卖出回购资产市值')
    mktv_sell_repo = Column(Numeric(22, 4), server_default=text("0.0000"), comment='买入返售市值')
    mktv_forward = Column(Numeric(22, 4), server_default=text("0.0000"), comment='远期投资市值')
    mktv_option = Column(Numeric(22, 4), server_default=text("0.0000"), comment='权证投资市值')
    cost_option = Column(Numeric(22, 4), server_default=text("0.0000"), comment='权证投资成本')
    total_deposit_amt = Column(Numeric(22, 4), server_default=text("0.0000"), comment='银行存款总金额（1002)')
    current_deposit_ai = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='活期存款应计利息')
    current_deposit_amt = Column(Numeric(22, 4), server_default=text("0.0000"), comment='活期存款金额（1002)')
    interest_receivable = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='应收利息金额（1204）')
    settlement_amt = Column(Numeric(22, 4), server_default=text("0.0000"), comment='证券清算款（3003）')
    capital_amt = Column(Numeric(22, 4), server_default=text("0.0000"), comment='实收资本金额（4001)')
    settlement_fund = Column(Numeric(22, 4), server_default=text("0.0000"), comment='结算备付金（1021）')
    settlement_fund_ai = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='备付金利息')
    margin_fund_ai = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='保证金利息')
    provision_fee = Column(Numeric(22, 4), server_default=text("0.0000"), comment='预提费用（2501）')
    subscribe_receivable_amt = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应收申购款(1207)')
    mktv_dividend_receivable = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应收股利（1203）')
    other_receivable_amt = Column(Numeric(22, 4), server_default=text("0.0000"), comment='其他应收款（1221）')
    payable_sales_fee = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付销售服务费（2208）')
    payable_custodian_fee = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付托管费（2207）')
    payable_tax = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付税费（2221）')
    payable_redemption_amt = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付赎回款（2203）')
    payable_redemption_fee = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付赎回费（2204）')
    payable_interest = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付利息（2231）')
    payable_profit = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付利润（2232）')
    payable_trading_fee = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付交易费（2209）')
    payable_mgt_fee = Column(Numeric(22, 4), server_default=text("0.0000"), comment='应付管理费（2206）')
    payable_other_amt = Column(Numeric(22, 4), server_default=text("0.0000"), comment='其他应付款（2241）')
    margin_fund = Column(Numeric(22, 4), server_default=text("0.0000"), comment='存出保证金（1031)')
    seven_days_ann_yield = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='七日年化收益')
    profitper10kshares = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='万份收益')
    total_profit_per10kshares = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='累计万份收益')
    nav_daily_growth_rate = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='日单位净值增长率')
    daily_return = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='日收益率')
    value_added_tax = Column(Numeric(22, 4), server_default=text("0.0000"), comment='增值税')
    edu_surcharge_tax = Column(Numeric(22, 4), server_default=text("0.0000"), comment='教育附加税')
    local_edu_surcharge_tax = Column(Numeric(22, 4), server_default=text("0.0000"), comment='地方教育附加税')
    construction_surcharge_tax = Column(Numeric(22, 4), server_default=text("0.0000"), comment='城建附加税')
    unamortized_fee = Column(Numeric(22, 4), server_default=text("0.0000"), comment='待摊费用（1501）')
    daily_income_realized = Column(Numeric(22, 4), server_default=text("0.0000"), comment='当日已实现收益')
    create_time = Column(DateTime, comment='创建时间')
    update_time = Column(DateTime, comment='更新时间')


class ValfileProductNetworth(Base):
    __tablename__ = 'valfile_product_networth'

    biz_date = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    net_date = Column(Date, nullable=False)
    product_code = Column(String(100), primary_key=True, nullable=False, comment='产品代码')
    product_name = Column(String(200))
    ta_acct_code = Column(String(100))
    ta_acct_name = Column(String(200))
    net_asset_mktv = Column(Numeric(22, 4), server_default=text("0.0000"))
    hld_shares = Column(Numeric(22, 4), server_default=text("0.0000"), comment='持有份额')
    total_shares = Column(Numeric(22, 4), server_default=text("0.0000"), comment='总份额')
    unit_nav = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='单位净值')
    virtual_unit_nav = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='虚拟单位净值')
    accu_unit_nav = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='累计单位净值')
    nav_growth_rate = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='单位净值增长率')
    accu_nav_growth_rate = Column(Numeric(22, 8), server_default=text("0.00000000"), comment='累计单位净值增长率')
    create_time = Column(DateTime, comment='创建时间')
    update_time = Column(DateTime, comment='更新时间')


class ValfileSecuPosDtl(Base):
    __tablename__ = 'valfile_secu_pos_dtl'
    __table_args__ = {'comment': '证券持仓表'}

    biz_date = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    product_code = Column(String(20), primary_key=True, nullable=False, comment='产品代码')
    portfolio_code = Column(String(20), server_default=text("NULL::character varying"), comment='投资组合代码')
    currency = Column(String(50), server_default=text("NULL::character varying"), comment='币种')
    exc_rate = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='汇率')
    ast_cls_code = Column(String(10), server_default=text("NULL::character varying"), comment='资产大类;股票、基金等')
    sec_type = Column(String(10), server_default=text("NULL::character varying"), comment='证券类型')
    market_code = Column(String(10), server_default=text("NULL::character varying"), comment='交易市场')
    inv_cls_code = Column(String(10), primary_key=True, nullable=False, comment='投资分类代码')
    lmt_cls_type_code = Column(String(10), primary_key=True, nullable=False, comment='受限流通类型代码')
    secu_code = Column(String(50), primary_key=True, nullable=False, comment='证券内码')
    hold_attr_code = Column(String(10), primary_key=True, nullable=False, comment='持有属性代码')
    hold_dir_code = Column(String(10), primary_key=True, nullable=False, comment='持仓方向')
    symbol = Column(String(50), server_default=text("NULL::character varying"), comment='证券代码')
    secu_name = Column(String(100), server_default=text("NULL::character varying"), comment='证券名称')
    hld_qty = Column(Numeric(18, 0), server_default=text("NULL::numeric"), comment='持仓数量')
    unit_cost_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='单位成本-原币')
    unit_cost_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='单位成本-本币')
    hld_cost_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='成本-原币')
    hld_cost_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='成本-本币')
    cost_nav_rate_o = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='成本占净值比例-原币')
    cost_nav_rate_l = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='成本占净值比例-本币')
    cost_ast_rate_o = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='成本占总资产比例-原币')
    cost_ast_rate_l = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='成本占总资产比例-本币')
    valuation_price = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='估值价格')
    hld_mktv_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='市值-原币')
    hld_mktv_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='市值-本币')
    mktv_nav_rate_o = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='市值占净值-原币')
    mktv_nav_rate_l = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='市值占净值-本币')
    mktv_ast_rate_o = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='市值占总资产-原币')
    mktv_ast_rate_l = Column(Numeric(22, 8), server_default=text("NULL::numeric"), comment='市值占总资产-本币')
    valuation_add_amt_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='估值增值-原币')
    valuation_add_amt_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='估值增值-本币')
    accd_interest_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='应计利息-原币')
    accd_interest_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='应计利息-本币')
    receivable_dividend_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='应收股利-原币')
    receivable_dividend_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='应收股利-本币')
    discount_premium_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='溢折价-原币')
    discount_premium_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='溢折价-本币')
    devalue_amt_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='减值准备-原币')
    devalue_amt_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='减值准备-本币')
    devalue_expense_o = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='减值损失-原币')
    devalue_expense_l = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='减值损失-本币')
    shadow_price = Column(Numeric(22, 4), server_default=text("NULL::numeric"), comment='影子价格')
    subpend_info = Column(String(200), server_default=text("NULL::character varying"), comment='停牌信息')
    rights_info = Column(String(200), server_default=text("NULL::character varying"), comment='权益信息')
    update_time = Column(DateTime)
