# coding: utf-8
from sqlalchemy import Column, DECIMAL, Date, DateTime, String, TIMESTAMP, text
from sqlalchemy.dialects.mysql import VARCHAR
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class INDICBASEBONDPOSDTL(Base):
    __tablename__ = 'INDIC_BASE_BOND_POS_DTL'
    __table_args__ = {'comment': '债券持仓明细表'}

    BIZ_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRD_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='产品代码')
    PORT_TYPE_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合类型代码')
    PORT_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合代码')
    SECU_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='证券内码')
    INVES_CLS_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资分类代码')
    AST_UNIT_CODE = Column(VARCHAR(50), comment='资产单元代码')
    STRGY_CODE = Column(VARCHAR(50), comment='策略代码')
    SUB_ACCT_CODE = Column(VARCHAR(50), comment='子账户代码')
    ISSUR_NUM = Column(VARCHAR(50), comment='发行人编码')
    SYMBOL = Column(VARCHAR(50), comment='证券代码')
    SECU_NAME = Column(VARCHAR(50), comment='证券名称')
    SECU_TYPE_CODE = Column(VARCHAR(50), comment='证券类型代码')
    TX_MKT_CODE = Column(VARCHAR(50), comment='交易市场代码')
    INT_PAY_MODE_CODE = Column(VARCHAR(50), comment='付息方式代码')
    INT_RATE_TYPE_CODE = Column(VARCHAR(50), comment='利率类型代码')
    CUR_CODE = Column(VARCHAR(50), comment='币种代码')
    UNIT_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='单位成本')
    VAL_PRC = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='估值价格')
    POS_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='持仓数量')
    LAST_DAY_POS_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='昨日持仓数量')
    ACTL_INT_RATE = Column(DECIMAL(15, 10), server_default=text("'0.0000000000'"), comment='实际利率')
    POS_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓成本')
    LAST_DAY_POS_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='昨日持仓成本')
    RMN_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='摊余成本')
    POS_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值')
    LAST_DAY_POS_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='昨日持仓市值')
    SHADOW_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='影子市值')
    RECVBL_INT_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='应计利息余额')
    VAL_ADD_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='估值增值余额')
    PREM_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='折溢价余额')
    ISSU_PAR = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='发行面值')
    TERM = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='期限')
    Y100_BON_INT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='百元债券利息')
    DEVAL_PREP_AMT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='减值准备金额')
    CURDAY_VAL_PAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日估值损益')
    CURDAY_BSIS_INCOM = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日差价收入')
    CURDAY_INT_INCOM = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日利息收入')
    POS_MKV_PORT_TOTL_AST_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合总资产比例')
    POS_MKV_PORT_AST_NAV_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合资产净值比例')
    POS_MKV_PORT_BON_MKV_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合债券市值比例')
    CREATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='更新时间')
    TX_FEE = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='交易费用')


class INDICBASESTOCKPOSDTL(Base):
    __tablename__ = 'INDIC_BASE_STOCK_POS_DTL'
    __table_args__ = {'comment': '股票持仓明细表'}

    BIZ_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRD_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='产品代码')
    PORT_TYPE_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合类型代码')
    PORT_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合代码')
    SECU_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='证券内码')
    LOCK_START_DATE = Column(Date, primary_key=True, nullable=False, server_default=text("'1970-01-01'"), comment='锁定开始日期')
    LMT_CIR_TYPE_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='受限流通类型代码')
    AST_UNIT_CODE = Column(VARCHAR(50), comment='资产单元代码')
    STRGY_CODE = Column(VARCHAR(50), comment='策略代码')
    SUB_ACCT_CODE = Column(VARCHAR(50), comment='子账户代码')
    LOCK_END_DATE = Column(Date, nullable=False, server_default=text("'1970-01-01'"), comment='锁定结束日期')
    GO_PUB_DATE = Column(Date, comment='上市日期')
    GO_PUB_STAT_CODE = Column(VARCHAR(50), comment='上市状态代码')
    GO_PUB_BRD = Column(VARCHAR(50), comment='上市板块')
    ISSUR_NUM = Column(VARCHAR(50), comment='发行人编码')
    SYMBOL = Column(VARCHAR(50), comment='证券代码')
    SECU_NAME = Column(VARCHAR(50), comment='证券名称')
    SECU_TYPE_CODE = Column(VARCHAR(50), comment='证券类型代码')
    TX_MKT_CODE = Column(VARCHAR(50), comment='交易市场代码')
    NP_ISSU_IND = Column(VARCHAR(3), comment='非公开发行标识')
    CUR_CODE = Column(VARCHAR(50), server_default=text("'CNY'"), comment='币种代码')
    EXR = Column(DECIMAL(15, 10), server_default=text("'0.0000000000'"), comment='汇率')
    VAL_PRC = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='估值价格')
    UNIT_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='单位成本')
    POS_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='持仓数量')
    POS_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓成本')
    POS_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值')
    LAST_DAY_POS_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='昨日持仓数量')
    LAST_DAY_POS_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='昨日持仓成本')
    LAST_DAY_POS_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='昨日持仓市值')
    RECVBL_DV_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='应收股利余额')
    VAL_ADD_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='估值增值余额')
    CURDAY_BSIS_INCOM = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日差价收入')
    CURDAY_VAL_PAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日估值损益')
    CURDAY_DV_INCOM = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日股利收入')
    POS_MKV_PORT_TOTL_AST_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合总资产比例')
    POS_MKV_PORT_AST_NAV_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合资产净值比例')
    POS_MKV_PORT_STK_MKV_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合股票市值比例')
    STOP_DATE = Column(Date, comment='停牌日期')
    LOCK_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='锁定数量')
    CONVT_RATIO = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='折算比例')
    REMN_LMT_SELL_PRD = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='剩余限售期')
    CREATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='更新时间')
    TX_FEE = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='交易费用')


class INDICBASETXBOND(Base):
    __tablename__ = 'INDIC_BASE_TX_BOND'
    __table_args__ = {'comment': '债券交易表'}

    TX_DATE = Column(Date, primary_key=True, nullable=False, comment='交易日期')
    TRAN_NUM = Column(VARCHAR(50), primary_key=True, nullable=False, comment='成交编号')
    PRD_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='产品代码')
    PORT_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合代码')
    AST_UNIT_CODE = Column(VARCHAR(50), comment='资产单元代码')
    STRGY_CODE = Column(VARCHAR(50), comment='策略代码')
    SUB_ACCT_CODE = Column(VARCHAR(50), comment='子账户代码')
    INSTR_NUM = Column(VARCHAR(50), comment='指令编号')
    SECU_CODE = Column(VARCHAR(100), comment='证券内码')
    SYMBOL = Column(VARCHAR(50), comment='证券代码')
    SECU_NAME = Column(VARCHAR(100), comment='证券名称')
    SECU_TYPE_CODE = Column(VARCHAR(50), comment='证券类型代码')
    TX_MKT_CODE = Column(VARCHAR(50), comment='交易市场代码')
    TX_TYPE_CODE = Column(VARCHAR(50), comment='交易类型代码')
    TX_CHNL_CODE = Column(VARCHAR(50), comment='交易渠道代码')
    INVES_CLS_CODE = Column(VARCHAR(50), comment='投资分类代码')
    CUR_CODE = Column(VARCHAR(50), comment='币种代码')
    CLR_DATE = Column(Date, comment='清算日期')
    ACTL_STL_DATE = Column(Date, comment='实际结算日期')
    CLR_SPEED = Column(DECIMAL(30, 0), comment='清算速度')
    TRAN_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='成交数量')
    TRAN_NET_PRC = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='成交净价格')
    TRAN_NET_AMT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='成交净金额')
    ACTL_STL_AMT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='实际结算金额')
    STL_FULL_PRC = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='结算全价')
    INT_AMT = Column(DECIMAL(30, 8), comment='利息')
    TX_FEE = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='交易费')
    CAC_FEE = Column(DECIMAL(30, 8), comment='证管费')
    HAND_FEE = Column(DECIMAL(30, 8), comment='经手费')
    COMM_FEE = Column(DECIMAL(30, 8), comment='手续费')
    STL_SERV_FEE = Column(DECIMAL(30, 8), comment='结算服务费')
    COMMSN_FEE = Column(DECIMAL(30, 8), comment='佣金费')
    CASH_ACCT_NUM = Column(VARCHAR(100), comment='现金账号')
    TX_CNT_PTY_CODE = Column(VARCHAR(50), comment='交易对手代码')
    TX_CNT_PTY_NAME = Column(VARCHAR(100), comment='交易对手名称')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='更新时间')
    TX_ACCT_NUM = Column(VARCHAR(50), comment='交易账号')
    EXR = Column(DECIMAL(30, 8), comment='汇率')


class INDICBASETXSTOCK(Base):
    __tablename__ = 'INDIC_BASE_TX_STOCK'
    __table_args__ = {'comment': '股票交易表'}

    TX_DATE = Column(Date, primary_key=True, nullable=False, comment='交易日期')
    TRAN_NUM = Column(VARCHAR(50), primary_key=True, nullable=False, comment='成交编号')
    PRD_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='产品代码')
    PORT_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合代码')
    AST_UNIT_CODE = Column(VARCHAR(50), comment='资产单元代码')
    STRGY_CODE = Column(VARCHAR(50), comment='策略代码')
    SUB_ACCT_CODE = Column(VARCHAR(50), comment='子账户代码')
    INSTR_NUM = Column(VARCHAR(50), comment='指令编号')
    SECU_CODE = Column(VARCHAR(100), comment='证券内码')
    SYMBOL = Column(VARCHAR(50), comment='证券代码')
    SECU_NAME = Column(VARCHAR(100), comment='证券名称')
    SECU_TYPE_CODE = Column(VARCHAR(50), comment='证券类型代码')
    TX_MKT_CODE = Column(VARCHAR(50), comment='交易市场代码')
    TX_TYPE_CODE = Column(VARCHAR(50), comment='交易类型代码')
    TX_CHNL_CODE = Column(VARCHAR(50), comment='交易渠道代码')
    STL_ORG_NUM = Column(VARCHAR(50), comment='结算机构代码')
    TX_INVES_AIM_CODE = Column(VARCHAR(50), comment='交易投资目的代码')
    INVES_CLS_CODE = Column(VARCHAR(50), comment='投资分类代码')
    CUR_CODE = Column(VARCHAR(50), comment='币种代码')
    CLR_DATE = Column(Date, comment='清算日期')
    TX_ACCT_NUM = Column(VARCHAR(100), comment='交易账号')
    CASH_ACCT_NUM = Column(VARCHAR(100), comment='资金账号')
    TX_CNT_PTY_CODE = Column(VARCHAR(50), comment='交易对手代码')
    TX_CNT_PTY_NAME = Column(VARCHAR(100), comment='交易对手名称')
    EXR = Column(DECIMAL(15, 10), comment='汇率')
    CLR_SPEED = Column(DECIMAL(30, 0), comment='清算速度')
    TRAN_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='成交数量')
    TRAN_PRC = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='成交价格')
    TRAN_AMT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='成交金额')
    STAMP_TAX = Column(DECIMAL(30, 8), comment='印花税')
    HAND_FEE = Column(DECIMAL(30, 8), comment='经手费')
    TRAN_FEE = Column(DECIMAL(30, 8), comment='过户费')
    CAC_FEE = Column(DECIMAL(30, 8), comment='证管费')
    TX_FEE = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='交易费')
    STL_SERV_FEE = Column(DECIMAL(30, 8), comment='结算服务费')
    COMMSN_FEE = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='佣金费')
    CREATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"), comment='更新时间')


class VALUATIONPORTIND(Base):
    __tablename__ = 'VALUATION_PORT_IND'

    BUSI_DATE = Column(Date, primary_key=True, nullable=False)
    PRODUCT_CODE = Column(String(100), primary_key=True, nullable=False)
    PORTFOLIO_TYPE = Column(String(100), primary_key=True, nullable=False)
    PORTFOLIO_CODE = Column(String(100), primary_key=True, nullable=False)
    TOTAL_ASSET_MKTV = Column(DECIMAL(22, 4))
    TOTAL_ASSET_COST = Column(DECIMAL(22, 4))
    TOTAL_LIABILITIES_MKTV = Column(DECIMAL(22, 4))
    TOTAL_LIABILITIES_COST = Column(DECIMAL(22, 4))
    NET_ASSET_MKTV = Column(DECIMAL(22, 4))
    NET_ASSET_COST = Column(DECIMAL(22, 4))
    SHARES = Column(DECIMAL(22, 4))
    UNIT_NAV = Column(DECIMAL(22, 8))
    ACCU_UNIT_NAV = Column(DECIMAL(22, 8))
    ACCU_NAV_GROWTH_RATE = Column(DECIMAL(22, 8))
    MKTV_STOCK = Column(DECIMAL(22, 4))
    COST_STOCK = Column(DECIMAL(22, 4))
    MKTV_BOND = Column(DECIMAL(22, 4))
    COST_BOND = Column(DECIMAL(22, 4))
    MKTV_FUND = Column(DECIMAL(22, 4))
    COST_FUND = Column(DECIMAL(22, 4))
    MKTV_ASSET_BACK = Column(DECIMAL(22, 4))
    COST_ASSET_BACK = Column(DECIMAL(22, 4))
    COST_NONSTD = Column(DECIMAL(22, 4))
    MKTV_NONSTD = Column(DECIMAL(22, 4))
    MKTV_FUTURE = Column(DECIMAL(22, 4))
    MKTV_BUY_REPO = Column(DECIMAL(22, 4))
    MKTV_SELL_REPO = Column(DECIMAL(22, 4))
    MKTV_FORWARD = Column(DECIMAL(22, 4))
    MKTV_OPTION = Column(DECIMAL(22, 4))
    COST_OPTION = Column(DECIMAL(22, 4))
    TOTAL_DEPOSIT_AMT = Column(DECIMAL(22, 4))
    CURRENT_DEPOSIT_AI = Column(DECIMAL(22, 8))
    CURRENT_DEPOSIT_AMT = Column(DECIMAL(22, 4))
    INTEREST_RECEIVABLE = Column(DECIMAL(22, 8))
    SETTLEMENT_AMT = Column(DECIMAL(22, 4))
    CAPITAL_AMT = Column(DECIMAL(22, 4))
    SETTLEMENT_FUND = Column(DECIMAL(22, 4))
    SETTLEMENT_FUND_AI = Column(DECIMAL(22, 8))
    MARGIN_FUND_AI = Column(DECIMAL(22, 8))
    PROVISION_FEE = Column(DECIMAL(22, 4))
    SUBSCRIBE_RECEIVABLE_AMT = Column(DECIMAL(22, 4))
    MKTV_DIVIDEND_RECEIVABLE = Column(DECIMAL(22, 4))
    OTHER_RECEIVABLE_AMT = Column(DECIMAL(22, 4))
    PAYABLE_SALES_FEE = Column(DECIMAL(22, 4))
    PAYABLE_CUSTODIAN_FEE = Column(DECIMAL(22, 4))
    PAYABLE_TAX = Column(DECIMAL(22, 4))
    PAYABLE_REDEMPTION_AMT = Column(DECIMAL(22, 4))
    PAYABLE_REDEMPTION_FEE = Column(DECIMAL(22, 4))
    PAYABLE_INTEREST = Column(DECIMAL(22, 4))
    PAYABLE_PROFIT = Column(DECIMAL(22, 4))
    PAYABLE_TRADING_FEE = Column(DECIMAL(22, 4))
    PAYABLE_MGT_FEE = Column(DECIMAL(22, 4))
    PAYABLE_OTHER_AMT = Column(DECIMAL(22, 4))
    MARGIN_FUND = Column(DECIMAL(22, 4))
    SEVEN_DAYS_ANN_YIELD = Column(DECIMAL(22, 8))
    PROFITPER10KSHARES = Column(DECIMAL(22, 8))
    TOTAL_PROFIT_PER10KSHARES = Column(DECIMAL(22, 8))
    NAV_DAILY_GROWTH_RATE = Column(DECIMAL(22, 8))
    DAILY_RETURN = Column(DECIMAL(22, 8))
    VALUE_ADDED_TAX = Column(DECIMAL(22, 4))
    EDU_SURCHARGE_TAX = Column(DECIMAL(22, 4))
    LOCAL_EDU_SURCHARGE_TAX = Column(DECIMAL(22, 4))
    CONSTRUCTION_SURCHARGE_TAX = Column(DECIMAL(22, 4))
    UNAMORTIZED_FEE = Column(DECIMAL(22, 4))
    DAILY_INCOME_REALIZED = Column(DECIMAL(22, 4))
    CREATE_TIME = Column(DateTime)
    UPDATE_TIME = Column(DateTime)


class VALUATIONPORTPOSDTL(Base):
    __tablename__ = 'VALUATION_PORT_POS_DTL'

    BUSI_DATE = Column(Date, primary_key=True, nullable=False)
    PRODUCT_CODE = Column(String(20), primary_key=True, nullable=False)
    PORTFOLIO_CODE = Column(String(20))
    CURRENCY = Column(String(50))
    EXC_RATE = Column(DECIMAL(22, 8))
    AST_CLS_CODE = Column(String(10))
    SEC_TYPE = Column(String(10))
    MARKET_CODE = Column(String(10))
    INV_CLS_CODE = Column(String(10), primary_key=True, nullable=False)
    LMT_CLS_TYPE_CODE = Column(String(10), primary_key=True, nullable=False)
    SECU_CODE = Column(String(50), primary_key=True, nullable=False)
    HOLD_ATTR_CODE = Column(String(10), primary_key=True, nullable=False)
    SYMBOL = Column(String(50))
    SECU_NAME = Column(String(100))
    HLD_QTY = Column(DECIMAL(18, 0))
    UNIT_COST_O = Column(DECIMAL(22, 4))
    UNIT_COST_L = Column(DECIMAL(22, 4))
    HLD_COST_O = Column(DECIMAL(22, 4))
    HLD_COST_L = Column(DECIMAL(22, 4))
    COST_NAV_RATE_O = Column(DECIMAL(22, 8))
    COST_NAV_RATE_L = Column(DECIMAL(22, 8))
    COST_AST_RATE_O = Column(DECIMAL(22, 8))
    COST_AST_RATE_L = Column(DECIMAL(22, 8))
    VALUATION_PRICE = Column(DECIMAL(22, 4))
    HLD_MKTV_O = Column(DECIMAL(22, 4))
    HLD_MKTV_L = Column(DECIMAL(22, 4))
    MKTV_NAV_RATE_O = Column(DECIMAL(22, 8))
    MKTV_NAV_RATE_L = Column(DECIMAL(22, 8))
    MKTV_AST_RATE_O = Column(DECIMAL(22, 8))
    MKTV_AST_RATE_L = Column(DECIMAL(22, 8))
    VALUATION_ADD_AMT_O = Column(DECIMAL(22, 4))
    VALUATION_ADD_AMT_L = Column(DECIMAL(22, 4))
    ACCD_INTEREST_O = Column(DECIMAL(22, 4))
    ACCD_INTEREST_L = Column(DECIMAL(22, 4))
    RECEIVABLE_DIVIDEND_O = Column(DECIMAL(22, 4))
    RECEIVABLE_DIVIDEND_L = Column(DECIMAL(22, 4))
    DISCOUNT_PREMIUM_O = Column(DECIMAL(22, 4))
    DISCOUNT_PREMIUM_L = Column(DECIMAL(22, 4))
    DEVALUE_AMT_O = Column(DECIMAL(22, 4))
    DEVALUE_AMT_L = Column(DECIMAL(22, 4))
    DEVALUE_EXPENSE_O = Column(DECIMAL(22, 4))
    DEVALUE_EXPENSE_L = Column(DECIMAL(22, 4))
    SHADOW_PRICE = Column(DECIMAL(22, 4))
    SUBPEND_INFO = Column(String(200))
    RIGHTS_INFO = Column(String(200))
    UPDATE_TIME = Column(DateTime)
