# coding: utf-8
from sqlalchemy import Column, DECIMAL, Date, DateTime, String, TIMESTAMP, text
from sqlalchemy.dialects.mysql import VARCHAR
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class INDICBASEBONDPOSDTL(Base):
    __tablename__ = 'INDIC_BASE_BOND_POS_DTL'
    __table_args__ = {'comment': '债券持仓明细表'}

    BIZ_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRD_CODE = Column(String(50), primary_key=True, nullable=False, comment='产品代码')
    PORT_TYPE_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合类型代码')
    PORT_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合代码')
    SECU_CODE = Column(String(50), primary_key=True, nullable=False, comment='证券内码')
    INVES_CLS_CODE = Column(String(50), primary_key=True, nullable=False, comment='投资分类代码')
    AST_UNIT_CODE = Column(String(50), comment='资产单元代码')
    STRGY_CODE = Column(String(50), comment='策略代码')
    SUB_ACCT_CODE = Column(String(50), comment='子账户代码')
    ISSUR_NUM = Column(String(50), comment='发行人编码')
    SYMBOL = Column(String(50), comment='证券代码')
    SECU_NAME = Column(String(50), comment='证券名称')
    SECU_TYPE_CODE = Column(String(50), comment='证券类型代码')
    TX_MKT_CODE = Column(String(50), comment='交易市场代码')
    INT_PAY_MODE_CODE = Column(String(50), comment='付息方式代码')
    INT_RATE_TYPE_CODE = Column(String(50), comment='利率类型代码')
    CUR_CODE = Column(String(50), comment='币种代码')
    UNIT_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='单位成本')
    VAL_PRC = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='估值价格')
    POS_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='持仓数量')
    LAST_DAY_POS_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='昨日持仓数量')
    ACTL_INT_RATE = Column(DECIMAL(15, 10), server_default=text("'0.0000000000'"), comment='实际利率')
    POS_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓成本')
    LAST_DAY_POS_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='昨日持仓成本')
    RMN_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='摊余成本')
    POS_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值')
    LAST_DAY_POS_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='昨日持仓市值')
    SHADOW_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='影子市值')
    RECVBL_INT_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='应计利息余额')
    VAL_ADD_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='估值增值余额')
    PREM_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='折溢价余额')
    ISSU_PAR = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='发行面值')
    TERM = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='期限')
    Y100_BON_INT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='百元债券利息')
    DEVAL_PREP_AMT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='减值准备金额')
    CURDAY_VAL_PAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日估值损益')
    CURDAY_BSIS_INCOM = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日差价收入')
    CURDAY_INT_INCOM = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日利息收入')
    POS_MKV_PORT_TOTL_AST_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合总资产比例')
    POS_MKV_PORT_AST_NAV_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合资产净值比例')
    POS_MKV_PORT_BON_MKV_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合债券市值比例')
    CREATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='更新时间')


class INDICBASESTOCKPOSDTL(Base):
    __tablename__ = 'INDIC_BASE_STOCK_POS_DTL'
    __table_args__ = {'comment': '股票持仓明细表'}

    BIZ_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRD_CODE = Column(String(50), primary_key=True, nullable=False, comment='产品代码')
    PORT_TYPE_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合类型代码')
    PORT_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='投资组合代码')
    SECU_CODE = Column(String(50), primary_key=True, nullable=False, comment='证券内码')
    LOCK_START_DATE = Column(Date, primary_key=True, nullable=False, server_default=text("'1970-01-01'"), comment='锁定开始日期')
    LMT_CIR_TYPE_CODE = Column(String(50), primary_key=True, nullable=False, comment='受限流通类型代码')
    INVES_CLS_CODE = Column(String(50), primary_key=True, nullable=False, comment='投资分类代码')
    AST_UNIT_CODE = Column(String(50), comment='资产单元代码')
    STRGY_CODE = Column(String(50), comment='策略代码')
    SUB_ACCT_CODE = Column(String(50), comment='子账户代码')
    LOCK_END_DATE = Column(Date, nullable=False, server_default=text("'1970-01-01'"), comment='锁定结束日期')
    GO_PUB_DATE = Column(Date, comment='上市日期')
    GO_PUB_STAT_CODE = Column(String(50), comment='上市状态代码')
    GO_PUB_BRD = Column(String(50), comment='上市板块')
    ISSUR_NUM = Column(String(50), comment='发行人编码')
    SYMBOL = Column(String(50), comment='证券代码')
    SECU_NAME = Column(String(50), comment='证券名称')
    SECU_TYPE_CODE = Column(String(50), comment='证券类型代码')
    TX_MKT_CODE = Column(String(50), comment='交易市场代码')
    NP_ISSU_IND = Column(String(3), comment='非公开发行标识')
    CUR_CODE = Column(VARCHAR(50), server_default=text("'CNY'"), comment='币种代码')
    EXR = Column(DECIMAL(15, 10), server_default=text("'0.0000000000'"), comment='汇率')
    VAL_PRC = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='估值价格')
    UNIT_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='单位成本')
    POS_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='持仓数量')
    POS_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓成本')
    POS_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值')
    LAST_DAY_POS_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='昨日持仓数量')
    LAST_DAY_POS_COST = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='昨日持仓成本')
    LAST_DAY_POS_MKV = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='昨日持仓市值')
    RECVBL_DV_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='应收股利余额')
    VAL_ADD_BAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='估值增值余额')
    CURDAY_BSIS_INCOM = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日差价收入')
    CURDAY_VAL_PAL = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日估值损益')
    CURDAY_DV_INCOM = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='当日股利收入')
    POS_MKV_PORT_TOTL_AST_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合总资产比例')
    POS_MKV_PORT_AST_NAV_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合资产净值比例')
    POS_MKV_PORT_STK_MKV_RAT = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='持仓市值占组合股票市值比例')
    STOP_DATE = Column(Date, comment='停牌日期')
    LOCK_QTY = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='锁定数量')
    CONVT_RATIO = Column(DECIMAL(30, 8), server_default=text("'0.00000000'"), comment='折算比例')
    REMN_LMT_SELL_PRD = Column(DECIMAL(30, 0), server_default=text("'0'"), comment='剩余限售期')
    CREATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='创建时间')
    UPDATE_TIME = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"), comment='更新时间')


class VALUATIONPORTIND(Base):
    __tablename__ = 'VALUATION_PORT_IND'
    __table_args__ = {'comment': '组合指标表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(String(100), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_TYPE = Column(String(100), primary_key=True, nullable=False, comment='投资组合类型')
    PORTFOLIO_CODE = Column(String(100), primary_key=True, nullable=False, comment='投资组合代码')
    TOTAL_ASSET_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总资产市值')
    TOTAL_ASSET_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总资产成本')
    TOTAL_LIABILITIES_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总负债市值')
    TOTAL_LIABILITIES_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='总负债成本')
    NET_ASSET_MKTV = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='净资产市值')
    NET_ASSET_COST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='净资产成本')
    SHARES = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='份额')
    UNIT_NAV = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='单位净值')
    ACCU_UNIT_NAV = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='累计单位净值')
    ACCU_NAV_GROWTH_RATE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='累计净值增长率')
    MKTV_STOCK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='股票投资市值')
    COST_STOCK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='股票投资成本')
    MKTV_BOND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='债券投资市值')
    COST_BOND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='债券投资成本')
    MKTV_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='基金投资市值')
    COST_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='基金投资成本')
    MKTV_ASSET_BACK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='资产支持证券市值')
    COST_ASSET_BACK = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='资产支持证券成本')
    COST_NONSTD = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='非标成本')
    MKTV_NONSTD = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='非标市值')
    MKTV_FUTURE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='期货投资市值')
    MKTV_BUY_REPO = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='卖出回购资产市值')
    MKTV_SELL_REPO = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='买入返售市值')
    MKTV_FORWARD = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='远期投资市值')
    MKTV_OPTION = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='权证投资市值')
    COST_OPTION = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='权证投资成本')
    TOTAL_DEPOSIT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='银行存款总金额（1002 银行存款）')
    CURRENT_DEPOSIT_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='活期存款应计利息')
    CURRENT_DEPOSIT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='活期存款金额（1002 银行存款 下级科目）')
    INTEREST_RECEIVABLE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='应收利息金额（1204）')
    SETTLEMENT_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='证券清算款（3003）')
    CAPITAL_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='实收资本金额（4001 实收基金）')
    SETTLEMENT_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='结算备付金（1021）')
    SETTLEMENT_FUND_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='备付金利息')
    MARGIN_FUND_AI = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='保证金利息')
    PROVISION_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='预提费用（2501）')
    SUBSCRIBE_RECEIVABLE_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收申购款(1207)')
    MKTV_DIVIDEND_RECEIVABLE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应收股利（1203）')
    OTHER_RECEIVABLE_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他应收款（1221）')
    PAYABLE_SALES_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付销售服务费（2208）')
    PAYABLE_CUSTODIAN_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付托管费（2207）')
    PAYABLE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付税费（2221）')
    PAYABLE_REDEMPTION_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付赎回款（2203）')
    PAYABLE_REDEMPTION_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付赎回费（2204）')
    PAYABLE_INTEREST = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付利息（2231）')
    PAYABLE_PROFIT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付利润（2232）')
    PAYABLE_TRADING_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付交易费（2209）')
    PAYABLE_MGT_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='应付管理费（2206）')
    PAYABLE_OTHER_AMT = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='其他应付款（2241）')
    MARGIN_FUND = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='存出保证金（1031 存出保证金）')
    SEVEN_DAYS_ANN_YIELD = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='七日年化收益')
    PROFITPER10KSHARES = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='万份收益')
    TOTAL_PROFIT_PER10KSHARES = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='累计万份收益')
    NAV_DAILY_GROWTH_RATE = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='日单位净值增长率')
    DAILY_RETURN = Column(DECIMAL(22, 8), server_default=text("'0.00000000'"), comment='日收益率')
    VALUE_ADDED_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='增值税')
    EDU_SURCHARGE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='教育附加税')
    LOCAL_EDU_SURCHARGE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='地方教育附加税')
    CONSTRUCTION_SURCHARGE_TAX = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='城建附加税')
    UNAMORTIZED_FEE = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='待摊费用（1501）')
    DAILY_INCOME_REALIZED = Column(DECIMAL(22, 4), server_default=text("'0.0000'"), comment='当日已实现收益')
    CREATE_TIME = Column(DateTime, comment='创建时间')
    UPDATE_TIME = Column(DateTime, comment='更新时间')


class VALUATIONPORTPOSDTL(Base):
    __tablename__ = 'VALUATION_PORT_POS_DTL'
    __table_args__ = {'comment': '组合持仓明细表'}

    BUSI_DATE = Column(Date, primary_key=True, nullable=False, comment='业务日期')
    PRODUCT_CODE = Column(VARCHAR(20), primary_key=True, nullable=False, comment='产品代码')
    PORTFOLIO_CODE = Column(VARCHAR(20), nullable=False, comment='投资组合代码')
    CURRENCY = Column(VARCHAR(50), comment='币种')
    EXC_RATE = Column(DECIMAL(22, 8), comment='汇率')
    AST_CLS_CODE = Column(VARCHAR(10), comment='资产大类，股票、基金等')
    SEC_TYPE = Column(VARCHAR(10), comment='证券类型')
    MARKET_CODE = Column(VARCHAR(10), comment='交易市场')
    INV_CLS_CODE = Column(VARCHAR(10), primary_key=True, nullable=False, comment='投资分类代码')
    LMT_CLS_TYPE_CODE = Column(VARCHAR(10), primary_key=True, nullable=False, comment='受限流通类型代码')
    SECU_CODE = Column(VARCHAR(50), primary_key=True, nullable=False, comment='证券内码')
    HOLD_ATTR_CODE = Column(VARCHAR(10), primary_key=True, nullable=False, comment='持有属性代码')
    SYMBOL = Column(VARCHAR(50), comment='证券代码')
    SECU_NAME = Column(VARCHAR(100), comment='证券名称')
    HLD_QTY = Column(DECIMAL(18, 0), comment='持仓数量')
    UNIT_COST_O = Column(DECIMAL(22, 4), comment='单位成本-原币')
    UNIT_COST_L = Column(DECIMAL(22, 4), comment='单位成本-本币')
    HLD_COST_O = Column(DECIMAL(22, 4), comment='成本-原币')
    HLD_COST_L = Column(DECIMAL(22, 4), comment='成本-本币')
    COST_NAV_RATE_O = Column(DECIMAL(22, 8), comment='成本占净值比例-原币')
    COST_NAV_RATE_L = Column(DECIMAL(22, 8), comment='成本占净值比例-本币')
    COST_AST_RATE_O = Column(DECIMAL(22, 8), comment='成本占总资产比例-原币')
    COST_AST_RATE_L = Column(DECIMAL(22, 8), comment='成本占总资产比例-本币')
    VALUATION_PRICE = Column(DECIMAL(22, 4), comment='估值价格')
    HLD_MKTV_O = Column(DECIMAL(22, 4), comment='市值-原币')
    HLD_MKTV_L = Column(DECIMAL(22, 4), comment='市值-本币')
    MKTV_NAV_RATE_O = Column(DECIMAL(22, 8), comment='市值占净值-原币')
    MKTV_NAV_RATE_L = Column(DECIMAL(22, 8), comment='市值占净值-本币')
    MKTV_AST_RATE_O = Column(DECIMAL(22, 8), comment='市值占总资产-原币')
    MKTV_AST_RATE_L = Column(DECIMAL(22, 8), comment='市值占总资产-本币')
    VALUATION_ADD_AMT_O = Column(DECIMAL(22, 4), comment='估值增值-原币')
    VALUATION_ADD_AMT_L = Column(DECIMAL(22, 4), comment='估值增值-本币')
    ACCD_INTEREST_O = Column(DECIMAL(22, 4), comment='应计利息-原币')
    ACCD_INTEREST_L = Column(DECIMAL(22, 4), comment='应计利息-本币')
    RECEIVABLE_DIVIDEND_O = Column(DECIMAL(22, 4), comment='应收股利-原币')
    RECEIVABLE_DIVIDEND_L = Column(DECIMAL(22, 4), comment='应收股利-本币')
    DISCOUNT_PREMIUM_O = Column(DECIMAL(22, 4), comment='溢折价-原币')
    DISCOUNT_PREMIUM_L = Column(DECIMAL(22, 4), comment='溢折价-本币')
    DEVALUE_AMT_O = Column(DECIMAL(22, 4), comment='减值准备-原币')
    DEVALUE_AMT_L = Column(DECIMAL(22, 4), comment='减值准备-本币')
    DEVALUE_EXPENSE_O = Column(DECIMAL(22, 4), comment='减值损失-原币')
    DEVALUE_EXPENSE_L = Column(DECIMAL(22, 4), comment='减值损失-本币')
    SHADOW_PRICE = Column(DECIMAL(22, 4), comment='影子价格')
    SUBPEND_INFO = Column(VARCHAR(200), comment='停牌信息')
    RIGHTS_INFO = Column(VARCHAR(200), comment='权益信息')
    UPDATE_TIME = Column(DateTime, comment='更新时间')
