[build-system]
requires = ["hatchling>=1.27,<2"]
build-backend = "hatchling.build"

[project]
name = "tools-vrp"
authors = [{ name = "fengbing", email = "bing.feng@iquantex.com" }]
readme = "readme.md"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: MIT License"]
description = "valuation report parser"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "SQLAlchemy==1.4.48",
    "PyMySQL==1.1.0",
    "psycopg2-binary==2.9.6",
    "openpyxl==3.0.10",
    "pyexcel==0.6.7",
    "pyexcel-xls==0.7.0",
    "pyexcel-xlsx==0.6.0",
    "python-dateutil==2.8.2",
    "cryptography==41.0.3",
]
optional-dependencies = { gauss = [
    "opengauss-sqlalchemy==2.1.0",
], test = ["pytest>=7,<10"] }

[project.urls]
Home = "https://www.iquantex.com"

[project.scripts]
vrp = "vrp.run:main"
tools = "vrp.tools:main"

[tool.hatch.version]
path = "vrp/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["vrp"]

[tool.hatch.build.targets.sdist]
include = ["/vrp", "/tests", "/pyproject.toml", "/readme.md", "/LICENSE", "/requirements.txt"]

[[tool.uv.index]]
name = "nexus"
url = "https://nexus-tzgl.szkingdom.com/repository/pypi-public/simple"
publish-url = "https://nexus-tzgl.szkingdom.com/repository/pypi-hosted/"
default = true
