[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tools-vrp"
authors = [{ name = "fengbing", email = "bing.feng@iquantex.com" }]
readme = "readme.md"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.6"
dependencies = [
    "SQLAlchemy>=1.4.48,<2",
    "PyMySQL>=1.1.0",
    "openpyxl>=3.0.10",
    "pyexcel>=0.6.7",
    "pyexcel-xls>=0.7.0",
    "pyexcel-xlsx>=0.6.0",
    "python-dateutil==2.8.2",
    "cryptography",
]
optional-dependencies = { gauss = [
    "psycopg2-binary==2.9.6",
    "opengauss-sqlalchemy==2.1.0",
] }

[project.urls]
Home = "https://www.iquantex.com"

[project.scripts]
vrp = "vrp.run:main"
tools = "vrp.tools:main"

[tool.flit.module]
name = "vrp"
